# Generated by Django 5.2 on 2025-05-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcommodity',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('q', 'Quintal'), ('t', 'Ton'), ('m', 'Metre'), ('cm', 'Centimetre'), ('in', 'Inch'), ('ft', 'Foot'), ('unit', 'Unit'), ('l', 'Litre'), ('ml', 'Millilitre')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='listcommodity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
