# Generated by Django 5.2 on 2025-05-10 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_listcommodity_unit_alter_listcommodity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcommodity',
            name='unit',
        ),
        migrations.AddField(
            model_name='suppliercommodity',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('q', 'Quintal'), ('t', 'Ton'), ('m', 'Metre'), ('cm', 'Centimetre'), ('in', 'Inch'), ('ft', 'Foot'), ('unit', 'Unit'), ('l', 'Litre'), ('ml', 'Millilitre')], default='unit', max_length=10),
        ),
        migrations.AlterField(
            model_name='listcommodity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliercommodity',
            name='available_units',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='suppliercommodity',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
