# Generated by Django 5.2 on 2025-06-11 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_listcommodity_unit_suppliercommodity_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listcommodity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listcommodity',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
